version: "2.4"
services:
  mockServer:
      image: mockserver/mockserver:latest
      ports:
        - 9090:9090
      environment:
        MOCKSERVER_SERVER_PORT: 9090
        MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
        MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
        MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserverInitialization.json
      volumes:
        - type: bind
          source: ./mockserver
          target: /config
      networks:  
      - testnet
  wallet:
    container_name: testing_wallet
    build:
      context: wallet
      dockerfile: Dockerfile
      args:
        - HOST_PAYMENTS=http://host.docker.internal:9090
        - BUNDLE_DEPLOYMENT=false
        - BUNDLE_WITHOUT=test
        - APP_HOME=/app
    command: bundle exec rackup -o 0.0.0.0 -p 8081
    volumes:
      - ./wallet:/app
    environment:
      HOST_PAYMENTS: http://host.docker.internal:9090
      RACK_ENV: development
      PORT: 8081
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
    depends_on:
      - mockServer
    networks:  
      - testnet
  certifier:
    container_name: testing_certifier
    build:
      context: certifier
      dockerfile: Dockerfile
      args:
        - BUNDLE_DEPLOYMENT=false
        - BUNDLE_WITHOUT=test
        - APP_HOME=/app
    command: ./run.sh
    volumes:
      - ./certifier:/app
    environment:
      RAILS_ENV: development
      PORT: 8082
    ports:
      - 8082:8082
    stdin_open: true
    tty: true
    networks:  
      - testnet
  web-api:
    container_name: testing_bff
    build:
      context: web-api
      dockerfile: Dockerfile
    command: java -jar /app/build/libs/web-api-0.0.1-SNAPSHOT.jar
    volumes:
      - ./web-api:/app
    environment:
      SPRING_PROFILES_ACTIVE: test
      HOST_WALLET: http://host.docker.internal:8081
      HOST_CERTIFIER: http://host.docker.internal:8082
      PORT: 8080
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    networks:
      - testnet
  web-ui:
    container_name: testing_ui
    build:
      context: web-ui
      dockerfile: Dockerfile
      target: runner
    command: yarn run dev
    volumes:
      - ./web-ui:/app
    environment:
      PORT: 3000
      NODE_ENV: development
      API_BASE_URI: http://testing_bff:8080
    ports:
      - 3000:3000
    depends_on:
      - web-api
      - certifier
      - wallet
    networks:  
      - testnet
networks:
  testnet:
    driver: bridge
